In [14]:
## leitura arquivo ponto_3.csv

import pandas as pd
import numpy as np


ponto = pd.DataFrame(pd.read_csv("/content/ponto_3.csv", sep=",", encoding='utf-8')) 

# limpeza da planilha
# substituindo valores nulos na coluna Contrato pela matricula do funcionário
ponto['Contrato'].fillna(method='ffill', inplace=True)

ponto

    Contrato        Data     Hor            Marcações Realizadas
0    20953.0  30/08/2021  3000.0                     13:14 19:16
1    20953.0  31/08/2021  3000.0         06:50 12:00 13:00 18:01
2    30317.0  30/08/2021  3064.0         15:35 20:00 21:00 00:05
3    30317.0  31/08/2021  3064.0         15:38 20:00 21:00 00:07
4    30399.0  30/08/2021  3063.0         07:38 12:00 13:00 16:08
5    30437.0  31/08/2021  3054.0         23:36 04:00 05:00 07:58
6    30438.0  29/08/2021     NaN        Repouso Remunerado 00:00
7    30438.0  30/08/2021  3052.0         07:39 12:00 13:00 16:00
8    30438.0  31/08/2021  3052.0         07:44 12:00 13:00 16:00
9    30439.0  30/08/2021     NaN  Repouso Remunerado 15:55 23:55
10   30458.0  31/08/2021     NaN          Compensado 23:55 07:55
11   30468.0  29/08/2021  3054.0                             NaN
12   30468.0  30/08/2021  3054.0                             NaN
13   30494.0  30/08/2021  3052.0         07:51 12:00 13:00 16:01
14   30539.0  29/08/2021  3053.0                     15:58 20:00
15   30541.0  29/08/2021  3052.0         07:42 12:00 13:00 16:04
16   30541.0  30/08/2021  3053.0         15:35 20:00 21:00 00:00
17   30541.0  31/08/2021  3053.0         15:31 20:00 21:00 00:00
18   30554.0  29/08/2021     NaN                Compensado 15:57
19   30554.0  30/08/2021     NaN        Repouso Remunerado 23:55
20   30563.0  30/08/2021  3000.0                             NaN
21   30563.0  31/08/2021  3000.0                             NaN
22   30596.0  31/08/2021  3052.0         07:56 12:00 13:00 16:06
23   30601.0  31/08/2021     NaN          Compensado 15:57 23:56
24   30606.0  31/08/2021  3054.0                     23:55 04:00
25   50104.0  29/08/2021  3054.0         23:43 04:00 05:00 08:00
26   50104.0  30/08/2021  3054.0         23:40 04:00 05:00 08:00

In [15]:
# eliminando linhas que indicam falta não justificada

ponto = ponto.dropna(subset=["Marcações Realizadas"])

In [16]:
# eliminando celulas que indicam que o funcionario estava de folga

ponto = ponto.dropna(subset=["Hor"])
ponto

    Contrato        Data     Hor     Marcações Realizadas
0    20953.0  30/08/2021  3000.0              13:14 19:16
1    20953.0  31/08/2021  3000.0  06:50 12:00 13:00 18:01
2    30317.0  30/08/2021  3064.0  15:35 20:00 21:00 00:05
3    30317.0  31/08/2021  3064.0  15:38 20:00 21:00 00:07
4    30399.0  30/08/2021  3063.0  07:38 12:00 13:00 16:08
5    30437.0  31/08/2021  3054.0  23:36 04:00 05:00 07:58
7    30438.0  30/08/2021  3052.0  07:39 12:00 13:00 16:00
8    30438.0  31/08/2021  3052.0  07:44 12:00 13:00 16:00
13   30494.0  30/08/2021  3052.0  07:51 12:00 13:00 16:01
14   30539.0  29/08/2021  3053.0              15:58 20:00
15   30541.0  29/08/2021  3052.0  07:42 12:00 13:00 16:04
16   30541.0  30/08/2021  3053.0  15:35 20:00 21:00 00:00
17   30541.0  31/08/2021  3053.0  15:31 20:00 21:00 00:00
22   30596.0  31/08/2021  3052.0  07:56 12:00 13:00 16:06
24   30606.0  31/08/2021  3054.0              23:55 04:00
25   50104.0  29/08/2021  3054.0  23:43 04:00 05:00 08:00
26   50104.0  30/08/2021  3054.0  23:40 04:00 05:00 08:00

In [4]:
# importando arquivo turnos

turnos = pd.DataFrame(pd.read_csv("/content/turnos3.csv", sep=";", encoding='utf-8')) 
turnos

           NOME    MATR. TURNO
0       GERSON   30433.0     A
1         JOSE   30435.0     A
2     VINICIUS   30609.0     A
3         ADÃO   30611.0     A
4         LUIS   30543.0     A
5     REINALDO   30595.0     A
6        PAULO       NaN     A
7      MARCELO   30541.0     A
8       Aislan   30622.0     A
9           NaN      NaN   NaN
10        JOAO   30449.0     B
11    ANDERSON   30485.0     B
12        LUIZ   30458.0     B
13     RODRIGO   30468.0     B
14      VALTER   30264.0     B
15        JOAO   30602.0     B
16     FABIANO   30601.0     B
17      WILSON   50104.0     B
18       JORGE   30502.0     B
19          NaN      NaN   NaN
20      MARCOS   30448.0     C
21      SANDRO       NaN     C
22      EMILIO   30436.0     C
23    JEFERSON   30439.0     C
24       ANDRÉ   30554.0     C
25      DANIEL   30463.0     C
26      DANILO   30474.0     C
27      CLEBER   30473.0     C
28      ELISEU   30623.0     C
29      VAGNER   30466.0     C
30       ARLEI   30339.0     C
31          NaN      NaN   NaN
32    MARCIELE   30613.0     D
33        JOAO   30398.0     D
34   CRISTIANO   30538.0     D
35    VILSOMAR   30550.0     D
36      DEIVID   30596.0     D
37  GRACILIANO   30453.0     D
38       GENTIL  30494.0     D
39      WILSON   30559.0     D
40          NaN      NaN   NaN
41       EDEIR   30503.0     E
42      SELMAR   30441.0     E
43     GIOVANI   30460.0     E
44    EDERALDO   30603.0     E
45      MOISES   30432.0     E
46       PAULO       NaN     E
47      GIEDER   30539.0     E
48       PAULO   30606.0     E
49     ANTONIO   30437.0     E
50       EDGAR   30599.0     E
51      FLAVIO   30644.0     E

In [17]:
ponto['Equipe'] = 'NaN'

for i, row in ponto.iterrows():
  for j, r in turnos.iterrows():
    if row['Contrato'] == r['MATR.']:
      ponto.loc[i,'Equipe'] =  turnos.loc[j,'TURNO']
      break
ponto

    Contrato        Data     Hor     Marcações Realizadas Equipe
0    20953.0  30/08/2021  3000.0              13:14 19:16    NaN
1    20953.0  31/08/2021  3000.0  06:50 12:00 13:00 18:01    NaN
2    30317.0  30/08/2021  3064.0  15:35 20:00 21:00 00:05    NaN
3    30317.0  31/08/2021  3064.0  15:38 20:00 21:00 00:07    NaN
4    30399.0  30/08/2021  3063.0  07:38 12:00 13:00 16:08    NaN
5    30437.0  31/08/2021  3054.0  23:36 04:00 05:00 07:58      E
7    30438.0  30/08/2021  3052.0  07:39 12:00 13:00 16:00    NaN
8    30438.0  31/08/2021  3052.0  07:44 12:00 13:00 16:00    NaN
13   30494.0  30/08/2021  3052.0  07:51 12:00 13:00 16:01      D
14   30539.0  29/08/2021  3053.0              15:58 20:00      E
15   30541.0  29/08/2021  3052.0  07:42 12:00 13:00 16:04      A
16   30541.0  30/08/2021  3053.0  15:35 20:00 21:00 00:00      A
17   30541.0  31/08/2021  3053.0  15:31 20:00 21:00 00:00      A
22   30596.0  31/08/2021  3052.0  07:56 12:00 13:00 16:06      D
24   30606.0  31/08/2021  3054.0              23:55 04:00      E
25   50104.0  29/08/2021  3054.0  23:43 04:00 05:00 08:00      B
26   50104.0  30/08/2021  3054.0  23:40 04:00 05:00 08:00      B